### PR TITLE
16.0

### PR DESCRIPTION
**Pull request by matteoopenf**
this two commit allow to work the module on odoo v16.0

### CODE REVIEW

**Comment by matteoopenf** [comment]
@JayVora-SerpentCS if you create the branch 16.0 I wil change the pull request

**Comment by ibradin88** [comment]
> @JayVora-SerpentCS if you create the branch 16.0 I wil change the pull request

What version (Java JDK/JRE) are you running? to run jasper module in Odoo version 16/17

**Comment by matteoopenf** [comment]
> > @JayVora-SerpentCS if you create the branch 16.0 I wil change the pull request
> 
> What version (Java JDK/JRE) are you running? to run jasper module in Odoo version 16/17

openjdk-11-jre groovy

**Comment by matteoopenf** [comment]
> > @JayVora-SerpentCS if you create the branch 16.0 I wil change the pull request
> 
> What version (Java JDK/JRE) are you running? to run jasper module in Odoo version 16/17

but yesterday I see some problem on v16.0

**Pull request merged**
