### PR TITLE
[FIX] Fixed xml generator and added the Quotation_template.pdf 'Inpro…

### PR DESCRIPTION
**Pull request by saif-serpentcs**
…cess'

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Please fix the travis asap

**Comment by saif-serpentcs** [comment]
@JayVora-SerpentCS Sure sir, I will.

Thanks.

**Comment by JayVora-SerpentCS** [comment]
The travis is still not fixd

**Comment by JayVora-SerpentCS** [comment]
Fix travis in an another PR plz.

**Comment by dcorio** [comment]
Hi @saif-serpentcs,
i've just tried to create a fresh db with demo data, but i get this while trying to print the quotation report:

```
Error:
Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:8069" from accessing a cross-origin frame.

http://localhost:8069/web/content/489-a1fa4b7/web.assets_common.js:3848
Traceback:
Error: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:8069" from accessing a cross-origin frame.
    at HTMLIFrameElement.<anonymous> (http://localhost:8069/web/content/489-a1fa4b7/web.assets_common.js:3848:246)
    at HTMLIFrameElement.dispatch (http://localhost:8069/web/content/489-a1fa4b7/web.assets_common.js:892:451)
    at HTMLIFrameElement.elemData.handle (http://localhost:8069/web/content/489-a1fa4b7/web.assets_common.js:865:173)
```

see #43

**Comment by saif-serpentcs** [comment]
ok, I will check soon.

**Comment by dcorio** [comment]
@saif-serpentcs That happens if the java_path field on the company is empty.
Not a real issue. You should probably just mention this on the readme as people is expecting you to check $JAVA_HOME by default.

**Comment by saif-serpentcs** [comment]
Exactly, set path in Java Path field **home/....../Jasperreports_odoo_11/jasper_reports/java/**

Thanks

**Comment by dcorio** [comment]
@saif-serpentcs so you're bundling the jre together with the odoo module. Another thing you should probably mention in the readme

In this case you should use this one by default, without the need to specify the java path by hand

**Comment by dcorio** [comment]
Just tried again to print the sample report. I'm now able to print a PDF but i just get a file which content is "%P"

**Pull request merged**
