### PR TITLE
[ADD]jasper_reports: Added images for Wiki.

### PR DESCRIPTION
**Pull request by hiren-serpentcs**
Added images for Wiki.

### CODE REVIEW

**Comment by saif-serpentcs** [comment]
@JayVora-SerpentCS Please, merge the branch.

**Comment by JayVora-SerpentCS** [comment]
Any reason why this was closed?

**Comment by hiren-serpentcs** [comment]
Since we have uploaded the Images from Image Hosting platform, there is no longer needed to put the Images on GitHub repo.
So we closed the PR.

**Comment by JayVora-SerpentCS** [comment]
So, where the wiki plz?

**Comment by hiren-serpentcs** [comment]
Sir we have placed the wiki in the [Documentation page](https://github.com/JayVora-SerpentCS/Jasperreports_odoo/wiki/Documentation).

**Pull request closed without merging**
